import {
  Activity,
  BadgeCheck,
  Bell,
  CalendarDays,
  CreditCard,
  Download,
  Gamepad2,
  Gauge,
  Gift,
  Headphones,
  Home,
  KeyRound,
  LayoutDashboard,
  Lock,
  MessageSquare,
  Music,
  Package,
  Palette,
  Radio,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Truck,
  UploadCloud,
  UserCircle,
  Users,
  Wallet
} from "lucide-react";
import type { LucideProps } from "lucide-react";
import type { IconName } from "@/config/navigation";

export const icons: Record<IconName, React.ComponentType<LucideProps>> = {
  activity: Activity,
  badge: BadgeCheck,
  bell: Bell,
  calendar: CalendarDays,
  "credit-card": CreditCard,
  download: Download,
  gamepad: Gamepad2,
  gauge: Gauge,
  gift: Gift,
  headphones: Headphones,
  home: Home,
  key: KeyRound,
  layout: LayoutDashboard,
  lock: Lock,
  message: MessageSquare,
  music: Music,
  package: Package,
  palette: Palette,
  radio: Radio,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  "shopping-bag": ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  truck: Truck,
  upload: UploadCloud,
  user: UserCircle,
  users: Users,
  wallet: Wallet
};
