#!/usr/bin/env python3

import hashlib
import io
import json
import os
from pathlib import Path

import cbor2
from PIL import Image, ImageDraw, ImageFont

LEVEL_DIRECTORY = Path(os.environ.get("CORE_FPS_PUBLISHED_LEVELS", "/tmp/core-published-levels"))
COMPILED_DIRECTORY = Path(os.environ.get("CORE_FPS_PUBLISHED_MAPS", "/tmp/core-published-maps"))
TEXTURE_DIRECTORY = Path(os.environ.get("CORE_FPS_LEVEL_TEXTURES", "/tmp/core-level-textures"))
ASSET_PREFIX = "packages/bouncecore/level-builder"


def font(size):
    font_path = os.environ.get(
        "CORE_FPS_ARENA_FONT",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    )
    try:
        return ImageFont.truetype(font_path, size)
    except OSError:
        return ImageFont.load_default(size=size)


def safe_text(value, fallback, maximum):
    text = " ".join(str(value or "").split())
    return (text or fallback)[:maximum]


def rgb(value, fallback=(20, 29, 42)):
    text = str(value or "")
    if len(text) == 7 and text.startswith("#"):
        try:
            return tuple(int(text[index : index + 2], 16) for index in (1, 3, 5))
        except ValueError:
            pass
    return fallback


def jpeg_bytes(image):
    output = io.BytesIO()
    image.convert("RGB").save(
        output,
        format="JPEG",
        quality=91,
        optimize=True,
        progressive=True,
        subsampling=0,
    )
    return output.getvalue()


def load_manifest():
    return json.loads((TEXTURE_DIRECTORY / "manifest.json").read_text(encoding="utf-8"))


def make_cfg(bundle, textures):
    document = bundle["document"]
    title = safe_text(document.get("name"), bundle["map"]["id"], 60).replace('"', "'")
    ambient = max(0, min(255, int(document.get("ambient", 96))))
    fog = max(128, min(16384, int(document.get("fog", 1800))))
    fog_color = rgb(document.get("fogColor"), (106, 168, 214))
    texture_lines = "\n".join(
        f'texture 0 "bouncecore/level-builder/{texture["id"]}.png"'
        for texture in textures
    )
    return f"""// Generated by the Bouncecore Core Level Builder
texturereset

setshader "stdworld"
{texture_lines}

maptitle "{title}"
ambient {ambient}
skylight 150 168 192
fog {fog}
fogcolour {fog_color[0]} {fog_color[1]} {fog_color[2]}
lightprecision 24
lighterror 4
"""


def make_preview(bundle, texture_lookup):
    document = bundle["document"]
    world_size = max(1, int(document.get("worldSize", 1024)))
    sky = rgb(document.get("skyColor"), (21, 31, 46))
    image = Image.new("RGB", (1280, 720), sky)
    draw = ImageDraw.Draw(image, "RGBA")
    draw.rectangle((0, 0, 1280, 92), fill=(5, 8, 15, 235))
    draw.text(
        (38, 18),
        safe_text(document.get("name"), "CUSTOM CORE ARENA", 60).upper(),
        font=font(46),
        fill=(255, 255, 255, 255),
    )
    modes = " / ".join(str(mode).upper() for mode in document.get("modes", []))
    draw.text((1010, 38), modes, font=font(20), fill=(0, 213, 255, 255), anchor="ra")

    arena = (64, 124, 1216, 676)
    draw.rectangle(arena, fill=(8, 13, 22, 235), outline=(0, 213, 255, 120), width=3)
    scale_x = (arena[2] - arena[0]) / world_size
    scale_y = (arena[3] - arena[1]) / world_size
    geometry = [
        obj
        for obj in document.get("objects", [])
        if obj.get("kind") == "geometry"
    ]
    geometry.sort(
        key=lambda obj: float(obj.get("transform", {}).get("position", {}).get("z", 0))
    )
    for obj in geometry:
        transform = obj.get("transform", {})
        position = transform.get("position", {})
        dimensions = transform.get("scale", {})
        x = float(position.get("x", 0))
        y = float(position.get("y", 0))
        width = max(2, float(dimensions.get("x", 1)) * scale_x)
        height = max(2, float(dimensions.get("y", 1)) * scale_y)
        left = arena[0] + x * scale_x - width / 2
        top = arena[3] - y * scale_y - height / 2
        definition = texture_lookup.get(obj.get("materialId"), {})
        color = rgb(definition.get("color"), (105, 115, 127))
        accent = rgb(definition.get("accent"), (210, 220, 230))
        draw.rectangle(
            (left, top, left + width, top + height),
            fill=color + (230,),
            outline=accent + (220,),
            width=2,
        )

    for obj in document.get("objects", []):
        if obj.get("kind") != "entity":
            continue
        position = obj.get("transform", {}).get("position", {})
        x = arena[0] + float(position.get("x", 0)) * scale_x
        y = arena[3] - float(position.get("y", 0)) * scale_y
        kind = obj.get("entityKind")
        color = (255, 43, 214) if kind == "flag" else (182, 255, 46)
        if kind == "player-spawn":
            team = int(obj.get("properties", {}).get("team", 0))
            color = (255, 65, 108) if team == 1 else (34, 189, 245) if team == 2 else (255, 255, 255)
        draw.ellipse((x - 7, y - 7, x + 7, y + 7), fill=color + (255,), outline=(5, 8, 15, 255), width=2)
    return image


def store_asset(asset_root, index, data, path):
    digest = hashlib.sha256(data).hexdigest()
    (asset_root / digest).write_bytes(data)
    if digest not in index["assets"]:
        index["assets"].append(digest)
    return [digest, path]


def update_runtime_map_pools(core_config, levels):
    if not levels:
        return
    preset_modes = {
        "default": None,
        "ffa": "ffa",
        "insta": "ffa",
        "team-deathmatch": "teamplay",
        "capture-the-flag": "ctf",
    }
    map_lines = {f'          - "{bundle["map"]["id"]}"' for bundle in levels}
    lines = [
        line
        for line in core_config.read_text(encoding="utf-8").splitlines()
        if line not in map_lines
    ]
    output = []
    preset = None
    for line in lines:
        stripped = line.strip()
        if line.startswith("    - name: "):
            preset = stripped.split(":", 1)[1].strip().strip('"')
        output.append(line)
        if line == "        maps:" and preset in preset_modes:
            required_mode = preset_modes[preset]
            for bundle in levels:
                modes = bundle.get("document", {}).get("modes", [])
                if required_mode is None or required_mode in modes:
                    output.append(f'          - "{bundle["map"]["id"]}"')
    core_config.write_text("\n".join(output) + "\n", encoding="utf-8")


def main():
    asset_root = Path(os.environ.get("CORE_FPS_ASSET_ROOT", "/opt/core/assets"))
    core_config = Path(os.environ.get("CORE_FPS_CONFIG", "/opt/core/core.yaml"))
    index_path = asset_root / ".index.source"
    manifest = load_manifest()
    textures = manifest["textures"]
    texture_lookup = {texture["id"]: texture for texture in textures}
    definition_paths = sorted(LEVEL_DIRECTORY.glob("*.json"))
    levels = [json.loads(path.read_text(encoding="utf-8")) for path in definition_paths]
    index = cbor2.loads(index_path.read_bytes())

    for bundle in levels:
        map_id = bundle["map"]["id"]
        if not map_id.startswith("bc-"):
            raise RuntimeError(f"Published map id is unsafe: {map_id}")
        map_prefix = f"packages/base/{map_id}"
        ogz_path = COMPILED_DIRECTORY / f"{map_id}.ogz"
        if not ogz_path.exists():
            raise RuntimeError(f"Compiled map is missing: {ogz_path}")

        payloads = [
            (ogz_path.read_bytes(), f"{map_prefix}.ogz"),
            (make_cfg(bundle, textures).encode("utf-8"), f"{map_prefix}.cfg"),
        ]
        payloads.extend(
            (
                (TEXTURE_DIRECTORY / f'{texture["id"]}.png').read_bytes(),
                f'{ASSET_PREFIX}/{texture["id"]}.png',
            )
            for texture in textures
        )
        payloads.append(
            (
                jpeg_bytes(make_preview(bundle, texture_lookup)),
                f"{map_prefix}.jpg",
            )
        )
        assets = [store_asset(asset_root, index, data, path) for data, path in payloads]
        lookup = {path: digest for digest, path in assets}
        ogz_hash = lookup[f"{map_prefix}.ogz"]
        preview_hash = lookup[f"{map_prefix}.jpg"]
        bundle_hash = hashlib.sha256(
            "\n".join(f"{digest}:{path}" for digest, path in assets).encode("utf-8")
        ).hexdigest()
        old_bundle_ids = {
            game_map.get("bundle")
            for game_map in index["maps"]
            if game_map.get("name") == map_id
        }
        index["maps"] = [
            game_map for game_map in index["maps"] if game_map.get("name") != map_id
        ]
        index["bundles"] = [
            item
            for item in index["bundles"]
            if item.get("id") not in old_bundle_ids and item.get("id") != bundle_hash
        ]
        index["bundles"].append(
            {
                "id": bundle_hash,
                "desktop": False,
                "web": False,
                "assets": assets,
            }
        )
        index["maps"].append(
            {
                "id": ogz_hash,
                "name": map_id,
                "ogz": ogz_hash,
                "bundle": bundle_hash,
                "assets": assets,
                "image": f"{preview_hash}.jpg",
                "description": safe_text(
                    bundle["document"].get("description"),
                    "A custom Bouncecore Core arena.",
                    500,
                ),
            }
        )

    index_path.write_bytes(cbor2.dumps(index))
    update_runtime_map_pools(core_config, levels)
    print(f"installed {len(levels)} published Core levels")


if __name__ == "__main__":
    main()
