#!/usr/bin/env bash
set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$APP_ROOT/.env.instance"
COMPOSE_FILE="$APP_ROOT/docker-compose.instance.yml"
BACKUP_ROOT="/srv/bouncecore-backups"
RETENTION_DAYS=14
REQUEST_VOLUME_PATH=".ops/backup-run-request.env"
STATUS_VOLUME_PATH=".ops/backup-run-status.env"

info() {
  printf '\n==> %s\n' "$1"
}

warn() {
  printf '\nWARNING: %s\n' "$1" >&2
}

die() {
  printf '\nERROR: %s\n' "$1" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: scripts/process-backup-requests.sh [options]

Options:
  --env-file PATH       Environment file to use. Default: .env.instance.
  --compose-file PATH   Compose file to use. Default: docker-compose.instance.yml.
  --backup-root PATH    Directory that receives dated backup folders. Default: /srv/bouncecore-backups.
  --retention-days N    Delete local dated backup folders older than N days. Default: 14.
  --request-volume-path PATH
                        Path inside uploads Docker volume for admin run requests. Default: .ops/backup-run-request.env.
  --status-volume-path PATH
                        Path inside uploads Docker volume for admin run status. Default: .ops/backup-run-status.env.
  -h, --help            Show this help.

This script is intended for a root-owned host timer. The web app only queues a
request file; this host-side processor runs Docker backups without exposing the
Docker socket to the web container.
USAGE
}

resolve_path() {
  local value="$1"

  case "$value" in
    /*) printf '%s' "$value" ;;
    *) printf '%s/%s' "$APP_ROOT" "$value" ;;
  esac
}

env_value() {
  local key="$1"
  local default_value="$2"
  local line
  local value

  line="$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)"

  if [ -z "$line" ]; then
    printf '%s' "$default_value"
    return
  fi

  value="${line#*=}"
  value="${value%$'\r'}"

  case "$value" in
    \"*\")
      value="${value#\"}"
      value="${value%\"}"
      ;;
    \'*\')
      value="${value#\'}"
      value="${value%\'}"
      ;;
  esac

  printf '%s' "$value"
}

file_value() {
  local file="$1"
  local key="$2"
  local default_value="$3"
  local line

  if [ ! -f "$file" ]; then
    printf '%s' "$default_value"
    return
  fi

  line="$(grep -E "^${key}=" "$file" | tail -n 1 || true)"

  if [ -z "$line" ]; then
    printf '%s' "$default_value"
    return
  fi

  printf '%s' "${line#*=}"
}

sanitize_status_value() {
  printf '%s' "$1" | tr '\r\n' ' ' | cut -c1-280
}

validate_volume_path() {
  local label="$1"
  local value="$2"

  case "$value" in
    *[!A-Za-z0-9._/-]*) die "$label supports only letters, numbers, dot, underscore, dash, and slash." ;;
    *..*) die "$label cannot contain '..'." ;;
    "") die "$label cannot be empty." ;;
  esac
}

resolve_docker_volume_name() {
  local configured_name="$1"
  local candidate

  if docker volume inspect "$configured_name" >/dev/null 2>&1; then
    printf '%s' "$configured_name"
    return
  fi

  while IFS= read -r candidate; do
    if [ "$candidate" = "$configured_name" ] || [ "${candidate%"_$configured_name"}" != "$candidate" ]; then
      printf '%s' "$candidate"
      return
    fi
  done < <(docker volume ls --format '{{.Name}}')

  printf '%s' "$configured_name"
}

write_status_to_uploads_volume() {
  local status="$1"
  local request_id="$2"
  local requested_at="$3"
  local requested_by="$4"
  local started_at="$5"
  local completed_at="$6"
  local exit_code="$7"
  local backup_dir="$8"
  local log_file="$9"
  local message="${10}"
  local target_path="${STATUS_VOLUME_PATH#/}"
  local target_dir
  local target_name
  local status_file

  target_dir="$(dirname "$target_path")"
  target_name="$(basename "$target_path")"
  status_file="$WORK_DIR/status.env"

  {
    printf '# Generated by Bouncecore host backup request processor.\n'
    printf 'status=%s\n' "$status"
    printf 'request_id=%s\n' "$request_id"
    printf 'requested_at=%s\n' "$requested_at"
    printf 'requested_by=%s\n' "$requested_by"
    printf 'started_at=%s\n' "$started_at"
    printf 'completed_at=%s\n' "$completed_at"
    printf 'exit_code=%s\n' "$exit_code"
    printf 'backup_dir=%s\n' "$backup_dir"
    printf 'log_file=%s\n' "$log_file"
    printf 'message=%s\n' "$(sanitize_status_value "$message")"
  } > "$status_file"

  docker run --rm -v "$UPLOADS_VOLUME:/uploads" -v "$status_file:/status.env:ro" alpine:3.20 sh -c "mkdir -p \"/uploads/$target_dir\" && chown 1001:65534 \"/uploads/$target_dir\" && chmod 775 \"/uploads/$target_dir\" && cp /status.env \"/uploads/$target_dir/$target_name\" && chmod 644 \"/uploads/$target_dir/$target_name\""
}

delete_request_from_uploads_volume() {
  local target_path="${REQUEST_VOLUME_PATH#/}"

  docker run --rm -v "$UPLOADS_VOLUME:/uploads" alpine:3.20 sh -c "rm -f \"/uploads/$target_path\""
}

copy_request_from_uploads_volume() {
  local target_path="${REQUEST_VOLUME_PATH#/}"

  docker run --rm -v "$UPLOADS_VOLUME:/uploads:ro" -v "$WORK_DIR:/work" alpine:3.20 sh -c "if [ -f \"/uploads/$target_path\" ]; then cp \"/uploads/$target_path\" /work/request.env; fi"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --env-file)
      [ "$#" -ge 2 ] || die "--env-file requires a path."
      ENV_FILE="$(resolve_path "$2")"
      shift 2
      ;;
    --compose-file)
      [ "$#" -ge 2 ] || die "--compose-file requires a path."
      COMPOSE_FILE="$(resolve_path "$2")"
      shift 2
      ;;
    --backup-root)
      [ "$#" -ge 2 ] || die "--backup-root requires a path."
      BACKUP_ROOT="$(resolve_path "$2")"
      shift 2
      ;;
    --retention-days)
      [ "$#" -ge 2 ] || die "--retention-days requires a number."
      RETENTION_DAYS="$2"
      shift 2
      ;;
    --request-volume-path)
      [ "$#" -ge 2 ] || die "--request-volume-path requires a path."
      REQUEST_VOLUME_PATH="$2"
      shift 2
      ;;
    --status-volume-path)
      [ "$#" -ge 2 ] || die "--status-volume-path requires a path."
      STATUS_VOLUME_PATH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

[ -f "$APP_ROOT/scripts/backup-instance.sh" ] || die "Missing backup script under $APP_ROOT."
[ -f "$ENV_FILE" ] || die "Missing environment file: $ENV_FILE"
[ -f "$COMPOSE_FILE" ] || die "Missing Compose file: $COMPOSE_FILE"
command -v docker >/dev/null 2>&1 || die "Docker is required."
[[ "$RETENTION_DAYS" =~ ^[0-9]+$ ]] || die "--retention-days must be a non-negative integer."
validate_volume_path "--request-volume-path" "$REQUEST_VOLUME_PATH"
validate_volume_path "--status-volume-path" "$STATUS_VOLUME_PATH"

UPLOADS_VOLUME="$(env_value UPLOADS_VOLUME bouncecore_uploads)"
UPLOADS_VOLUME="$(resolve_docker_volume_name "$UPLOADS_VOLUME")"

if ! docker volume inspect "$UPLOADS_VOLUME" >/dev/null 2>&1; then
  die "Uploads Docker volume does not exist: $UPLOADS_VOLUME"
fi

mkdir -p "$BACKUP_ROOT"
BACKUP_ROOT="$(cd "$BACKUP_ROOT" && pwd)"

LOCK_DIR="$BACKUP_ROOT/.admin-backup-request.lock"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  warn "Another backup request processor is already running."
  exit 0
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"; rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT

copy_request_from_uploads_volume

if [ ! -f "$WORK_DIR/request.env" ]; then
  info "No admin backup request queued."
  exit 0
fi

REQUEST_ID="$(file_value "$WORK_DIR/request.env" request_id "")"
REQUESTED_AT="$(file_value "$WORK_DIR/request.env" requested_at "")"
REQUESTED_BY="$(file_value "$WORK_DIR/request.env" requested_by "")"

if [[ ! "$REQUEST_ID" =~ ^[A-Za-z0-9_.:-]{8,80}$ ]] || [ -z "$REQUESTED_AT" ] || [ -z "$REQUESTED_BY" ]; then
  write_status_to_uploads_volume failed "$REQUEST_ID" "$REQUESTED_AT" "$REQUESTED_BY" "" "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "2" "" "" "Backup request file is invalid and was not executed."
  delete_request_from_uploads_volume
  die "Invalid admin backup request file."
fi

STARTED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
LOG_FILE="$BACKUP_ROOT/admin-backup-request-$REQUEST_ID.log"

write_status_to_uploads_volume running "$REQUEST_ID" "$REQUESTED_AT" "$REQUESTED_BY" "$STARTED_AT" "" "" "" "$LOG_FILE" "Manual backup request is running."

info "Running manual backup request $REQUEST_ID"
set +e
(
  cd "$APP_ROOT"
  bash scripts/backup-instance.sh --env-file "$ENV_FILE" --compose-file "$COMPOSE_FILE" --backup-root "$BACKUP_ROOT" --retention-days "$RETENTION_DAYS"
) > "$LOG_FILE" 2>&1
EXIT_CODE="$?"
set -e

chmod 600 "$LOG_FILE" || true
COMPLETED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
LATEST_BACKUP_DIR="$(file_value "$BACKUP_ROOT/latest-backup.env" backup_dir "")"

if [ "$EXIT_CODE" -eq 0 ]; then
  write_status_to_uploads_volume completed "$REQUEST_ID" "$REQUESTED_AT" "$REQUESTED_BY" "$STARTED_AT" "$COMPLETED_AT" "$EXIT_CODE" "$LATEST_BACKUP_DIR" "$LOG_FILE" "Manual verified backup completed successfully."
else
  write_status_to_uploads_volume failed "$REQUEST_ID" "$REQUESTED_AT" "$REQUESTED_BY" "$STARTED_AT" "$COMPLETED_AT" "$EXIT_CODE" "$LATEST_BACKUP_DIR" "$LOG_FILE" "Manual backup failed. Inspect the host log file."
fi

delete_request_from_uploads_volume
exit "$EXIT_CODE"
