ALTER TABLE "DigitalTrack" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DigitalTrack" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX "DigitalTrack_createdAt_idx" ON "DigitalTrack"("createdAt");
