import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { writeAuditLog } from "@/lib/auth/audit";

export const backupRunRequestVolumePath = ".ops/backup-run-request.env";
export const backupRunStatusVolumePath = ".ops/backup-run-status.env";

export type BackupRunStatusValue = "none" | "queued" | "running" | "completed" | "failed" | "unknown";

export type BackupRunRequest = {
  requestId: string;
  requestedAt: string;
  requestedBy: string;
};

export type BackupRunStatus = {
  backupDir: string | null;
  completedAt: string | null;
  exitCode: number | null;
  logFile: string | null;
  message: string;
  requestId: string | null;
  requestedAt: string | null;
  requestedBy: string | null;
  startedAt: string | null;
  status: BackupRunStatusValue;
};

export type BackupRunHealthCheck = {
  detail: string;
  href?: string;
  label: string;
  status: "healthy" | "warning" | "critical";
  value: string;
};

export type AdminBackupRunData = {
  canRequest: boolean;
  request: BackupRunRequest | null;
  requestFilePath: string;
  requestVolumePath: string;
  status: BackupRunStatus;
  statusFilePath: string;
  statusVolumePath: string;
};

function uploadsOpsPath(volumePath: string) {
  return path.resolve(process.cwd(), "public", "uploads", volumePath);
}

export function backupRunRequestFilePath() {
  return uploadsOpsPath(backupRunRequestVolumePath);
}

export function backupRunStatusFilePath() {
  return process.env.BACKUP_RUN_STATUS_FILE?.trim() || uploadsOpsPath(backupRunStatusVolumePath);
}

export function parseBackupEnvFile(input: string) {
  const values = new Map<string, string>();

  for (const line of input.split(/\r?\n/)) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) {
      continue;
    }

    const [key, ...valueParts] = trimmed.split("=");
    values.set(key.trim(), valueParts.join("=").trim());
  }

  return values;
}

function safeText(value: string | null | undefined, maxLength: number) {
  const text = value?.trim() ?? "";

  if (!text) {
    return null;
  }

  return text.slice(0, maxLength);
}

function safeInteger(value: string | null | undefined) {
  if (!value) {
    return null;
  }

  const parsed = Number(value);

  return Number.isInteger(parsed) ? parsed : null;
}

function isBackupRunStatusValue(value: string): value is BackupRunStatusValue {
  return ["queued", "running", "completed", "failed", "unknown"].includes(value);
}

export function backupRunRequestFromValues(values: Map<string, string>): BackupRunRequest | null {
  const requestId = safeText(values.get("request_id"), 80);
  const requestedAt = safeText(values.get("requested_at"), 40);
  const requestedBy = safeText(values.get("requested_by"), 120);

  if (!requestId || !requestedAt || !requestedBy || !/^[A-Za-z0-9_.:-]+$/.test(requestId)) {
    return null;
  }

  return {
    requestId,
    requestedAt,
    requestedBy
  };
}

export function backupRunStatusFromValues(values: Map<string, string>): BackupRunStatus {
  const rawStatus = safeText(values.get("status"), 40) ?? "unknown";
  const status = isBackupRunStatusValue(rawStatus) ? rawStatus : "unknown";

  return {
    backupDir: safeText(values.get("backup_dir"), 320),
    completedAt: safeText(values.get("completed_at"), 40),
    exitCode: safeInteger(values.get("exit_code")),
    logFile: safeText(values.get("log_file"), 320),
    message: safeText(values.get("message"), 280) ?? "No manual backup request has been processed yet.",
    requestId: safeText(values.get("request_id"), 80),
    requestedAt: safeText(values.get("requested_at"), 40),
    requestedBy: safeText(values.get("requested_by"), 120),
    startedAt: safeText(values.get("started_at"), 40),
    status
  };
}

function emptyBackupRunStatus(): BackupRunStatus {
  return {
    backupDir: null,
    completedAt: null,
    exitCode: null,
    logFile: null,
    message: "No manual backup request has been processed yet.",
    requestId: null,
    requestedAt: null,
    requestedBy: null,
    startedAt: null,
    status: "none"
  };
}

function backupRunRequestToEnv(request: BackupRunRequest) {
  return [
    "# Generated by Bouncecore admin. Host backup timer consumes this request.\n",
    `request_id=${request.requestId}\n`,
    `requested_at=${request.requestedAt}\n`,
    `requested_by=${request.requestedBy}\n`
  ].join("");
}

function backupRunStatusToEnv(status: BackupRunStatus) {
  return [
    "# Generated by Bouncecore admin. Host backup timer updates this file.\n",
    `status=${status.status}\n`,
    `request_id=${status.requestId ?? ""}\n`,
    `requested_at=${status.requestedAt ?? ""}\n`,
    `requested_by=${status.requestedBy ?? ""}\n`,
    `started_at=${status.startedAt ?? ""}\n`,
    `completed_at=${status.completedAt ?? ""}\n`,
    `exit_code=${status.exitCode ?? ""}\n`,
    `backup_dir=${status.backupDir ?? ""}\n`,
    `log_file=${status.logFile ?? ""}\n`,
    `message=${status.message.replace(/[\r\n]/g, " ").slice(0, 280)}\n`
  ].join("");
}

async function atomicWriteFile(filePath: string, content: string, mode = 0o600) {
  await mkdir(path.dirname(filePath), { recursive: true });

  const tempFile = `${filePath}.${process.pid}.${Date.now()}.tmp`;

  await writeFile(tempFile, content, { mode });
  await rename(tempFile, filePath);
}

async function fileExists(filePath: string) {
  try {
    const fileStat = await stat(/* turbopackIgnore: true */ filePath);

    return fileStat.isFile();
  } catch {
    return false;
  }
}

export async function readBackupRunRequest(): Promise<BackupRunRequest | null> {
  const requestFile = backupRunRequestFilePath();

  try {
    return backupRunRequestFromValues(parseBackupEnvFile(await readFile(/* turbopackIgnore: true */ requestFile, "utf8")));
  } catch {
    return null;
  }
}

export async function readBackupRunStatus(): Promise<BackupRunStatus> {
  const statusFile = backupRunStatusFilePath();

  try {
    return backupRunStatusFromValues(parseBackupEnvFile(await readFile(/* turbopackIgnore: true */ statusFile, "utf8")));
  } catch {
    return emptyBackupRunStatus();
  }
}

export async function getAdminBackupRunData(): Promise<AdminBackupRunData> {
  const [request, status, requestFilePresent] = await Promise.all([
    readBackupRunRequest(),
    readBackupRunStatus(),
    fileExists(backupRunRequestFilePath())
  ]);
  const activeStatus = status.status === "queued" || status.status === "running";

  return {
    canRequest: !requestFilePresent && !activeStatus,
    request,
    requestFilePath: backupRunRequestFilePath(),
    requestVolumePath: backupRunRequestVolumePath,
    status,
    statusFilePath: backupRunStatusFilePath(),
    statusVolumePath: backupRunStatusVolumePath
  };
}

function dateAgeMinutes(value: string | null, now: Date) {
  if (!value) {
    return null;
  }

  const parsed = new Date(value);

  if (!Number.isFinite(parsed.getTime())) {
    return null;
  }

  return Math.max(0, Math.round((now.getTime() - parsed.getTime()) / 60 / 1000));
}

function formatAgeMinutes(minutes: number | null) {
  if (minutes === null) {
    return "unknown age";
  }

  if (minutes < 60) {
    return `${minutes} minutes`;
  }

  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;

  return remainingMinutes ? `${hours}h ${remainingMinutes}m` : `${hours}h`;
}

export function manualBackupRunHealthCheckFromData(
  data: Pick<AdminBackupRunData, "request" | "status">,
  {
    now = new Date(),
    queuedWarningMinutes = 5,
    runningWarningMinutes = 180
  }: {
    now?: Date;
    queuedWarningMinutes?: number;
    runningWarningMinutes?: number;
  } = {}
): BackupRunHealthCheck {
  const request = data.request;
  const status = data.status;
  const href = "/admin/storage";

  if (status.status === "running") {
    const ageMinutes = dateAgeMinutes(status.startedAt, now);
    const stale = ageMinutes === null || ageMinutes > runningWarningMinutes;

    return {
      detail: stale
        ? `Manual backup request ${status.requestId ?? "unknown"} has been running for ${formatAgeMinutes(ageMinutes)}. Check bouncecore-backup-request.service and the host log.`
        : `Manual backup request ${status.requestId ?? "unknown"} has been running for ${formatAgeMinutes(ageMinutes)}.`,
      href,
      label: "Manual backup requests",
      status: stale ? "warning" : "healthy",
      value: stale ? "Long running" : "Running"
    };
  }

  if (status.status === "queued" || request) {
    const queuedAt = request?.requestedAt ?? status.requestedAt;
    const requestId = request?.requestId ?? status.requestId ?? "unknown";
    const ageMinutes = dateAgeMinutes(queuedAt, now);
    const stale = ageMinutes === null || ageMinutes > queuedWarningMinutes;

    return {
      detail: stale
        ? `Manual backup request ${requestId} has been queued for ${formatAgeMinutes(ageMinutes)}. The host request timer may not be processing uploads volume requests.`
        : `Manual backup request ${requestId} is queued and waiting for the host request timer.`,
      href,
      label: "Manual backup requests",
      status: stale ? "warning" : "healthy",
      value: stale ? "Queued too long" : "Queued"
    };
  }

  if (status.status === "failed") {
    return {
      detail: status.message || "The last manual backup request failed. Check the host backup request log.",
      href,
      label: "Manual backup requests",
      status: "warning",
      value: "Last failed"
    };
  }

  if (status.status === "completed") {
    return {
      detail: status.completedAt
        ? `Last manual backup request completed at ${status.completedAt}. Backup: ${status.backupDir ?? "not recorded"}`
        : "Last manual backup request completed.",
      href,
      label: "Manual backup requests",
      status: "healthy",
      value: "Last completed"
    };
  }

  if (status.status === "unknown") {
    return {
      detail: "Manual backup request status file exists but has an unrecognized status.",
      href,
      label: "Manual backup requests",
      status: "warning",
      value: "Unknown"
    };
  }

  return {
    detail: "No manual backup request is currently queued or running.",
    href,
    label: "Manual backup requests",
    status: "healthy",
    value: "Idle"
  };
}

export async function queueManualBackupRun(actorId: string) {
  const current = await getAdminBackupRunData();

  if (!current.canRequest) {
    throw new Error("A manual backup is already queued or running. Wait for it to complete before requesting another backup.");
  }

  const request: BackupRunRequest = {
    requestId: randomUUID(),
    requestedAt: new Date().toISOString(),
    requestedBy: actorId
  };
  const status: BackupRunStatus = {
    ...emptyBackupRunStatus(),
    message: "Manual backup request queued. The host backup request timer should pick this up within about a minute.",
    requestId: request.requestId,
    requestedAt: request.requestedAt,
    requestedBy: request.requestedBy,
    status: "queued"
  };

  await atomicWriteFile(backupRunRequestFilePath(), backupRunRequestToEnv(request));
  await atomicWriteFile(backupRunStatusFilePath(), backupRunStatusToEnv(status), 0o644);

  await writeAuditLog({
    actorId,
    action: "backup.manual.queue",
    target: `backup-request:${request.requestId}`,
    severity: "warning",
    metadata: {
      requestVolumePath: backupRunRequestVolumePath,
      statusVolumePath: backupRunStatusVolumePath
    }
  });

  return request;
}
