import { randomBytes } from "node:crypto";
import { mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Prisma } from "@prisma/client";
import {
  googleDriveRcloneConfigVolumePath,
  googleDriveRcloneDestination,
  normalizeGoogleDriveFolder,
  normalizeGoogleDriveRemoteName
} from "@/lib/admin/offsite-backup-targets";
import { getOffsiteBackupSettings, updateOffsiteBackupSettings } from "@/lib/admin/offsite-backup-settings";
import { writeAuditLog } from "@/lib/auth/audit";
import { prisma } from "@/lib/db/prisma";
import { appUrl } from "@/lib/http/app-url";

const googleDriveBackupSettingKey = "backup.google_drive_oauth";
const googleDriveOAuthScope = "https://www.googleapis.com/auth/drive.file";
export const googleDriveOAuthCookieName = "bouncecore_gdrive_oauth";

export { googleDriveRcloneConfigVolumePath } from "@/lib/admin/offsite-backup-targets";

export type GoogleDriveOAuthState = {
  actorId: string;
  folder: string;
  issuedAt: string;
  remoteName: string;
  state: string;
};

export type GoogleDriveBackupConnection = {
  configFilePath: string;
  configFilePresent: boolean;
  connected: boolean;
  connectedAt: string | null;
  destination: string;
  folder: string;
  oauthConfigured: boolean;
  remoteName: string;
  setupDetail: string;
  volumePath: string;
};

type GoogleTokenResponse = {
  access_token?: string;
  error?: string;
  error_description?: string;
  expires_in?: number;
  refresh_token?: string;
  scope?: string;
  token_type?: string;
};

function googleClientId() {
  return process.env.GOOGLE_DRIVE_OAUTH_CLIENT_ID?.trim() ?? "";
}

function googleClientSecret() {
  return process.env.GOOGLE_DRIVE_OAUTH_CLIENT_SECRET?.trim() ?? "";
}

export function googleDriveOAuthConfigured() {
  return Boolean(googleClientId() && googleClientSecret());
}

function isObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function defaultConnectionRecord(remoteName: string, folder: string) {
  return {
    connectedAt: null,
    folder,
    remoteName
  };
}

function mergeConnectionRecord(value: unknown, fallbackRemoteName: string, fallbackFolder: string) {
  const fallback = defaultConnectionRecord(fallbackRemoteName, fallbackFolder);

  if (!isObject(value)) {
    return fallback;
  }

  return {
    connectedAt: typeof value.connectedAt === "string" ? value.connectedAt : null,
    folder: typeof value.folder === "string" ? normalizeGoogleDriveFolder(value.folder) : fallback.folder,
    remoteName: typeof value.remoteName === "string" ? normalizeGoogleDriveRemoteName(value.remoteName) : fallback.remoteName
  };
}

export function googleDriveRcloneConfigFilePath() {
  return path.resolve(process.cwd(), "public", "uploads", googleDriveRcloneConfigVolumePath);
}

async function googleDriveRcloneConfigExists() {
  try {
    const fileStat = await stat(/* turbopackIgnore: true */ googleDriveRcloneConfigFilePath());

    return fileStat.isFile();
  } catch {
    return false;
  }
}

function normalizeOAuthText(value: string, label: string) {
  const text = value.trim();

  if (!text || /[\r\n]/.test(text)) {
    throw new Error(`${label} is missing or invalid.`);
  }

  return text;
}

function tokenExpiry(expiresIn: number | undefined, now = new Date()) {
  const seconds = Number.isFinite(expiresIn) && expiresIn ? Math.max(60, Math.trunc(expiresIn)) : 3600;

  return new Date(now.getTime() + seconds * 1000).toISOString();
}

export function googleDriveTokenToRcloneToken(token: GoogleTokenResponse, now = new Date()) {
  const accessToken = normalizeOAuthText(token.access_token ?? "", "Google Drive access token");
  const refreshToken = normalizeOAuthText(token.refresh_token ?? "", "Google Drive refresh token");

  return JSON.stringify({
    access_token: accessToken,
    expiry: tokenExpiry(token.expires_in, now),
    refresh_token: refreshToken,
    token_type: token.token_type ?? "Bearer"
  });
}

export function googleDriveRcloneConfigContent({
  clientId,
  clientSecret,
  remoteName,
  token
}: {
  clientId: string;
  clientSecret: string;
  remoteName: string;
  token: string;
}) {
  const safeRemoteName = normalizeGoogleDriveRemoteName(remoteName);

  return [
    "# Generated by Bouncecore Google Drive authorization. Do not edit manually.\n",
    `[${safeRemoteName}]\n`,
    "type = drive\n",
    "scope = drive.file\n",
    `client_id = ${normalizeOAuthText(clientId, "Google Drive OAuth client ID")}\n`,
    `client_secret = ${normalizeOAuthText(clientSecret, "Google Drive OAuth client secret")}\n`,
    `token = ${normalizeOAuthText(token, "Google Drive OAuth token")}\n`
  ].join("");
}

async function writeGoogleDriveRcloneConfig({
  remoteName,
  token
}: {
  remoteName: string;
  token: GoogleTokenResponse;
}) {
  const configFile = googleDriveRcloneConfigFilePath();
  const content = googleDriveRcloneConfigContent({
    clientId: googleClientId(),
    clientSecret: googleClientSecret(),
    remoteName,
    token: googleDriveTokenToRcloneToken(token)
  });

  await mkdir(path.dirname(configFile), { recursive: true });
  await writeFile(configFile, content, { mode: 0o600 });

  return configFile;
}

export function createGoogleDriveOAuthState(actorId: string, remoteName: string, folder: string): GoogleDriveOAuthState {
  return {
    actorId,
    folder: normalizeGoogleDriveFolder(folder),
    issuedAt: new Date().toISOString(),
    remoteName: normalizeGoogleDriveRemoteName(remoteName),
    state: randomBytes(24).toString("base64url")
  };
}

export function encodeGoogleDriveOAuthStateCookie(state: GoogleDriveOAuthState) {
  return Buffer.from(JSON.stringify(state), "utf8").toString("base64url");
}

export function decodeGoogleDriveOAuthStateCookie(value: string | undefined): GoogleDriveOAuthState | null {
  if (!value) {
    return null;
  }

  try {
    const parsed = JSON.parse(Buffer.from(value, "base64url").toString("utf8")) as Partial<GoogleDriveOAuthState>;

    if (!parsed.actorId || !parsed.folder || !parsed.issuedAt || !parsed.remoteName || !parsed.state) {
      return null;
    }

    const issuedAt = new Date(parsed.issuedAt);

    if (!Number.isFinite(issuedAt.getTime()) || Date.now() - issuedAt.getTime() > 15 * 60 * 1000) {
      return null;
    }

    return {
      actorId: parsed.actorId,
      folder: normalizeGoogleDriveFolder(parsed.folder),
      issuedAt: parsed.issuedAt,
      remoteName: normalizeGoogleDriveRemoteName(parsed.remoteName),
      state: parsed.state
    };
  } catch {
    return null;
  }
}

export function googleDriveOAuthRedirectUri(request: Request) {
  return appUrl(request, "/admin/storage/google-drive/callback").toString();
}

export function googleDriveAuthorizationUrl(request: Request, state: GoogleDriveOAuthState) {
  if (!googleDriveOAuthConfigured()) {
    throw new Error("GOOGLE_DRIVE_OAUTH_CLIENT_ID and GOOGLE_DRIVE_OAUTH_CLIENT_SECRET must be configured before Google Drive can be connected.");
  }

  const url = new URL("https://accounts.google.com/o/oauth2/v2/auth");

  url.searchParams.set("access_type", "offline");
  url.searchParams.set("client_id", googleClientId());
  url.searchParams.set("include_granted_scopes", "true");
  url.searchParams.set("prompt", "consent");
  url.searchParams.set("redirect_uri", googleDriveOAuthRedirectUri(request));
  url.searchParams.set("response_type", "code");
  url.searchParams.set("scope", googleDriveOAuthScope);
  url.searchParams.set("state", state.state);

  return url;
}

export async function exchangeGoogleDriveAuthorizationCode(request: Request, code: string): Promise<GoogleTokenResponse> {
  if (!googleDriveOAuthConfigured()) {
    throw new Error("Google Drive OAuth credentials are missing.");
  }

  const response = await fetch("https://oauth2.googleapis.com/token", {
    body: new URLSearchParams({
      client_id: googleClientId(),
      client_secret: googleClientSecret(),
      code,
      grant_type: "authorization_code",
      redirect_uri: googleDriveOAuthRedirectUri(request)
    }),
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    method: "POST"
  });
  const body = (await response.json().catch(() => ({}))) as GoogleTokenResponse;

  if (!response.ok || body.error) {
    throw new Error(body.error_description || body.error || "Google Drive authorization failed.");
  }

  if (!body.access_token || !body.refresh_token) {
    throw new Error("Google did not return an offline refresh token. Try connecting again and approve offline access.");
  }

  return body;
}

export async function getGoogleDriveBackupConnection(
  remoteName: string | null | undefined,
  folder: string | null | undefined
): Promise<GoogleDriveBackupConnection> {
  const safeRemoteName = normalizeGoogleDriveRemoteName(remoteName);
  const safeFolder = normalizeGoogleDriveFolder(folder);
  const setting = await prisma.appSetting.findUnique({
    where: {
      key: googleDriveBackupSettingKey
    }
  });
  const connection = mergeConnectionRecord(setting?.value, safeRemoteName, safeFolder);
  const configFilePresent = await googleDriveRcloneConfigExists();

  return {
    configFilePath: googleDriveRcloneConfigFilePath(),
    configFilePresent,
    connected: Boolean(setting && configFilePresent),
    connectedAt: connection.connectedAt,
    destination: googleDriveRcloneDestination(connection.remoteName, connection.folder),
    folder: connection.folder,
    oauthConfigured: googleDriveOAuthConfigured(),
    remoteName: connection.remoteName,
    setupDetail: googleDriveOAuthConfigured()
      ? "Google Drive OAuth credentials are configured. Owners can connect Google Drive from this page."
      : "Set GOOGLE_DRIVE_OAUTH_CLIENT_ID and GOOGLE_DRIVE_OAUTH_CLIENT_SECRET, then restart the app before connecting Google Drive.",
    volumePath: googleDriveRcloneConfigVolumePath
  };
}

export async function completeGoogleDriveBackupOAuth({
  actorId,
  folder,
  remoteName,
  request,
  token
}: {
  actorId: string;
  folder: string;
  remoteName: string;
  request: Request;
  token: GoogleTokenResponse;
}) {
  const safeRemoteName = normalizeGoogleDriveRemoteName(remoteName);
  const safeFolder = normalizeGoogleDriveFolder(folder);
  const connectedAt = new Date().toISOString();
  const configFile = await writeGoogleDriveRcloneConfig({
    remoteName: safeRemoteName,
    token
  });

  await prisma.appSetting.upsert({
    where: {
      key: googleDriveBackupSettingKey
    },
    update: {
      description: "Google Drive backup OAuth connection metadata. Token material is written to the protected rclone config file.",
      isSecret: true,
      value: {
        connectedAt,
        folder: safeFolder,
        remoteName: safeRemoteName
      } satisfies Prisma.InputJsonValue
    },
    create: {
      description: "Google Drive backup OAuth connection metadata. Token material is written to the protected rclone config file.",
      isSecret: true,
      key: googleDriveBackupSettingKey,
      value: {
        connectedAt,
        folder: safeFolder,
        remoteName: safeRemoteName
      } satisfies Prisma.InputJsonValue
    }
  });

  await writeAuditLog({
    actorId,
    action: "backup.google_drive.connect",
    target: `google-drive:${safeRemoteName}`,
    severity: "warning",
    metadata: {
      callbackOrigin: new URL(request.url).origin,
      configFile,
      destination: googleDriveRcloneDestination(safeRemoteName, safeFolder),
      folder: safeFolder,
      remoteName: safeRemoteName,
      tokenScope: token.scope ?? googleDriveOAuthScope
    }
  });

  const existing = await getOffsiteBackupSettings();

  return updateOffsiteBackupSettings(
    {
      ageRecipient: existing.settings.ageRecipient,
      destinationType: "google-drive",
      enabled: existing.settings.enabled,
      googleDriveFolder: safeFolder,
      googleDriveRemoteName: safeRemoteName,
      outputDir: existing.settings.outputDir,
      rcloneRemote: googleDriveRcloneDestination(safeRemoteName, safeFolder),
      removeLocalAfterUpload: existing.settings.removeLocalAfterUpload
    },
    actorId
  );
}
